### ISSUE TITLE
Make API ignore db prefix

### ISSUE THREAD

**Issue by joeunrue** [aliscott/cloud-pricing-api#2]
Hi, I don't know if this is a silly request or not, but could you detect and ignore the `db.` prefix in front of instance types? For instance, change `db.r5.2xlarge` to `r5.2xlarge`. I see that Infracost is trying to look up an instance type but it cannot because that instance type technically doesn't exist. Amazon states they use the same pricing for database instances as they are for standard ones: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_OnDemandDBInstances.html

**Comment by alikhajeh1** [comment]
@joeunrue thanks for taking time to report the issue. The cloud-pricing-api already has RDS prices, which have instanceTypes prefixed with `db.`.

I checked various `db.r5.2xlarge` prices and I found an issue with Oracle prices that might have caused your issue (fixed in https://github.com/aliscott/infracost/pull/17). Were you by any chance using `oracle-se2` for `engine`? If not, can you please provide details of a terraform aws_db_instance resource that is failing for you so I can dig into it more?

**Comment by joeunrue** [comment]
Did a little research and you are checking for postgresql but the engine name specified by AWS is postgres

```Engine
The name of the database engine to be used for this instance.

Not every database engine is available for every AWS Region.

Valid Values:

aurora (for MySQL 5.6-compatible Aurora)
aurora-mysql (for MySQL 5.7-compatible Aurora)
aurora-postgresql
mariadb
mysql
oracle-ee
oracle-se2
oracle-se1
oracle-se
postgres
sqlserver-ee
sqlserver-se
sqlserver-ex
sqlserver-web
Type: String

Required: Yes
```

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

**Comment by joeunrue** [comment]
I'm going to close this issue because it is not with this application but with infracost. I opened a pull request there: https://github.com/aliscott/infracost/pull/18
